# Generated by Django 3.2.8 on 2022-02-19 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=0, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999'. Up to 15 digits allowed.", regex='^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$')])),
                ('address_name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=17)),
                ('province', models.CharField(default='', max_length=17)),
                ('state', models.CharField(default='', max_length=17)),
                ('zip', models.CharField(default=0, max_length=7, validators=[django.core.validators.RegexValidator(message="Zip Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
