# Generated by Django 3.2.8 on 2021-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
    ]
