# Generated by Django 3.2.8 on 2022-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='contact_name',
            field=models.CharField(default='', max_length=17),
        ),
    ]
