# Generated by Django 3.2.8 on 2022-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_payment_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
