# Generated by Django 3.2.8 on 2022-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220221_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
