# Generated by Django 3.2.8 on 2022-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='contact_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
