# Generated by Django 3.2.8 on 2022-02-18 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220218_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zip',
            field=models.CharField(default=0, max_length=7, validators=[django.core.validators.RegexValidator(message="Zip Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')]),
        ),
    ]
