# Generated by Django 3.2.8 on 2022-02-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraddress_zip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
