# Generated by Django 3.2.8 on 2021-11-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author_ids',
            new_name='book_author',
        ),
    ]
