# Generated by Django 3.2.8 on 2021-11-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_author_ids_book_book_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
    ]
