# Generated by Django 3.2.8 on 2022-02-08 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220123_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(default='', through='book.BookAuthor', to='book.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
