# Generated by Django 3.2.8 on 2022-02-21 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='contact_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999'. Up to 15 digits allowed.", regex='^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
