# Generated by Django 3.2.8 on 2022-02-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('book', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
