# Generated by Django 3.2.8 on 2021-10-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(blank=True, max_length=8, null=True)),
                ('language_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'book_language',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'db_table': 'book_author',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_author_ids',
            field=models.ManyToManyField(through='book.BookAuthor', to='book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.booklanguage'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.publisher'),
        ),
    ]
